# Generated by Django 4.0.5 on 2022-06-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=256)),
                ('local', models.CharField(max_length=80)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('iscompleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
